### ISSUE TITLE
Port original fine-tuned checkpoint to TFHub

### ISSUE THREAD

**Issue by vasudevgupta7** [vasudevgupta7/gsoc-wav2vec2#10]
Hello @sayakpaul @MorganR,

1st checkpoint is up here: https://tfhub.dev/vasudevgupta7/wav2vec2/1 🎉 🎉 

Now, I can transfer 2nd checkpoint to TFHub. It's the converted checkpoint which was fine-tuned on LibriSpeech dataset by Facebook (TensorFlow equivalent of [this](https://huggingface.co/facebook/wav2vec2-base-960h)). I think, we can make changes to [this notebook](https://github.com/vasudevgupta7/gsoc-wav2vec2/blob/main/notebooks/librispeech-evaluation.ipynb) and link it with our 2nd checkpoint.

Please give your valuable suggestions/comments on that.

**Comment by sayakpaul** [comment]
Congratulations, @vasudevgupta7  🥳 Be sure to update this in the README of this repository and other places you think are relevant. 

Just a nit: why is the architecture field blank? 

<img width="719" alt="Screenshot 2021-07-29 at 7 13 36 AM" src="https://user-images.githubusercontent.com/22957388/127418633-e5c0f8e4-b44b-45a1-9eb9-32458751de1c.png">

@MorganR is this a known bug? 

> Now, I can transfer 2nd checkpoint to TFHub. It's the converted checkpoint which was fine-tuned on LibriSpeech dataset by Facebook (TensorFlow equivalent of this). I think, we can make changes to this notebook and link it with our 2nd checkpoint.

Sounds good. However, help me understand this. I see TensorFlow model weights here:

<img width="1257" alt="Screenshot 2021-07-29 at 7 16 58 AM" src="https://user-images.githubusercontent.com/22957388/127418777-8ebec823-a1c6-4996-82a8-01d6e5d4ab2d.png">

Is it equivalent to what you have used in [your notebook](https://github.com/vasudevgupta7/gsoc-wav2vec2/blob/main/notebooks/librispeech-evaluation.ipynb)? Also when the LibriSpeech fine-tuning would be complete (the one you are working on) should match the results that you have got in the notebook, right?

**Comment by vasudevgupta7** [comment]
I am not sure about blank architecture field. Am I missing something in the [PR](https://github.com/tensorflow/tfhub.dev/commit/312a037515c2085a1b8e47da2f75a21ec8bcc847) or it's just a bug??

These TF weights (which I am planning to add to TFHub) are converted from `pytorch_model.bin` (from above screen shot). Those are converted using [this script](https://github.com/vasudevgupta7/gsoc-wav2vec2/blob/main/src/convert_torch_to_tf.py) and are used in many tests ([see this](https://github.com/vasudevgupta7/gsoc-wav2vec2/blob/559f361c187455248343a6c8828d6e2909afdb84/tests/test_wav2vec2.py#L51)). I have also used it in [my notebook](https://github.com/vasudevgupta7/gsoc-wav2vec2/blob/main/notebooks/librispeech-evaluation.ipynb).

`tf_model.h5` (in above screen shot) is different from our checkpoint (HuggingFace also recently added TF version of Wav2Vec2).

Yes, our fine-tuned checkpoint (once training is over) should give same results (ideally) compared to this checkpoint if trained exactly the same way done by Facebook. Do you think it's good idea to send "converted fine-tuned" checkpoint to TFHub as well as they are came with the paper??

**Comment by sayakpaul** [comment]
> tf_model.h5 (in above screen shot) is different from our checkpoint (HuggingFace also recently added TF version of Wav2Vec2).

Could you elaborate a bit more on this as in what aspects they are different? Maybe I am missing out on something. 

> Do you think it's good idea to send "converted fine-tuned" checkpoint to TFHub as well as they came with the paper??

I think if our fine-tuned checkpoints produce similar results on the evaluation set, then it's fine to only export that to Hub.

**Comment by MorganR** [comment]
Don't worry about the architecture tag. It's a known issue that it takes a
few days for a new tag value in yaml to show up on the frontend.

**Comment by vasudevgupta7** [comment]
> > tf_model.h5 (in above screen shot) is different from our checkpoint (HuggingFace also recently added TF version of Wav2Vec2).
> 
> Could you elaborate a bit more on this as in what aspects they are different? Maybe I am missing out on something.
> 

HuggingFace also added TF Wav2Vec2 in Transformers, so they also converted Wav2Vec2 from their pytorch version to TF. So their converted model & mine converted model are completely equivalent in terms of outputs but my conversion script is very different from theirs. So layers naming, weights naming is different and their TF checkpoint doesn't work with my code.

> > Do you think it's good idea to send "converted fine-tuned" checkpoint to TFHub as well as they came with the paper??
> 
> I think if our fine-tuned checkpoints produce similar results on the evaluation set, then it's fine to only export that to Hub.

okay

**Comment by sayakpaul** [comment]
> HuggingFace also added TF Wav2Vec2 in Transformers, so they also converted Wav2Vec2 from their pytorch version to TF. So their converted model & mine converted model are completely equivalent in terms of outputs but my conversion script is very different from theirs. So layers naming, weights naming is different and their TF checkpoint doesn't work with my code.

Thanks for the clarification.
