### ISSUE TITLE
unable to create TPU node

### ISSUE THREAD

**Issue by vasudevgupta7** [vasudevgupta7/gsoc-wav2vec2#11]
Hello @sayakpaul @MorganR ,

I am unable to create TPU node since last 2 days. I am getting following error:

```
ERROR: (gcloud.compute.tpus.execution-groups.create) There is no more capacity in the zone "europe-west4-a"; you can try in another zone where Cloud TPU Nodes are offered (see https://cloud.google.com/tpu/docs/regions) [EID: 0xba393c906974e61]
```

As I have v3-8 access only in `europe-west-4a` region, so can't create node in other regions. Is there any solution to above issue or I will have to just wait?

**Comment by sayakpaul** [comment]
Unfortunately, it's a burnout problem. @jaeyounkim any suggestions?

**Comment by MorganR** [comment]
Agreed with Sayak, unfortunately I think you will have to wait.
