### ISSUE TITLE
Fused conv implementation error when running fine-tuning notebook 

### ISSUE THREAD

**Issue by spn259** [vasudevgupta7/gsoc-wav2vec2#25]
Hi,

I'm getting this error when running the following lines in the fune-tuning notebook for Wav2Vec.

`model(tf.random.uniform(shape=(BATCH_SIZE, AUDIO_MAXLEN)))`

```
UnimplementedError:  Fused conv implementation does not support grouped convolutions for now.
	 [[{{node StatefulPartitionedCall/wav2vec2/encoder/pos_conv_embed/conv/Conv1DWithWeightNorm}}]] [Op:__inference_restored_function_body_38644]
```

This is with Python 3.7, and Tensorflow 2.7.0.

Any idea the issue?

Thanks!

**Comment by vasudevgupta7** [comment]
Hey, You need to wrap model forward pass into jit_compile=True when working with graph mode on CPU.

**Comment by vasudevgupta7** [comment]
Assuming this issue would be resolved by now. Hence closing this issue.
