### ISSUE TITLE
Error in accompanying Colab: "Failed to get convolution algorithm"

### ISSUE THREAD

**Issue by evanrmurphy** [vasudevgupta7/gsoc-wav2vec2#29]
In the [accompanying Colab](https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/wav2vec2_saved_model_finetuning.ipynb#scrollTo=oPp18ZHRtnq-), under **Setting up training state** at this step:

```
model(tf.random.uniform(shape=(BATCH_SIZE, AUDIO_MAXLEN)))
model.summary()
```

Running all the code in the colab up to this point produces an error here:

```
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
<ipython-input-7-59995e55f4ed> in <module>()
----> 1 model(tf.random.uniform(shape=(BATCH_SIZE, AUDIO_MAXLEN)))
      2 model.summary()

11 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node StatefulPartitionedCall/wav2vec2/feature_extractor/conv_layers/0/conv/conv1d}}]] [Op:__inference_restored_function_body_38644]

Function call stack:
restored_function_body
```

Here's a screenshot:

<img width="1437" alt="Screen Shot 2022-01-09 at 1 38 39 PM" src="https://user-images.githubusercontent.com/362851/148697945-86dca664-7a70-4b45-8bf7-4333040a21b3.png">

**Comment by evanrmurphy** [comment]
I get the same error on this other wav2vec2 Colab: https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/wav2vec2_saved_model_finetuning.ipynb#scrollTo=ZgL5wyaXZvM-

**Update: I meant to link to a different Colab from the one I posted in this original issue, but it looks like I ended up pasting the same link. 🤔 If I find the other one I'll follow up.**

**Comment by thevasudevgupta** [comment]
discussed in #30. You should be able to run the notebooks now!! I have fixed the issue in the `main` branch.

**Comment by evanrmurphy** [comment]
Thank you! I confirmed that everything runs successfully for me in [the notebook](https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/wav2vec2_saved_model_finetuning.ipynb) now. :)
