### ISSUE TITLE
Error in accompanying Colab: "InternalError: libdevice not found at ./libdevice.10.bc [Op:__inference_tf_forward_55230]"

### ISSUE THREAD

**Issue by evanrmurphy** [vasudevgupta7/gsoc-wav2vec2#30]
In an [accompanying Colab](https://colab.research.google.com/github/vasudevgupta7/gsoc-wav2vec2/blob/main/notebooks/librispeech_evaluation_WER_6.ipynb#scrollTo=AmvU-_otsGIG) (different Colab than for #29), under **Setting up training state** at this step:

```
predictions, labels = infer_librispeech(dataset, num_batches=2618)
```

Running all the code in the colab up to this point produces an error here:

```
---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
<ipython-input-16-85b57072fd5d> in <module>()
----> 1 predictions, labels = infer_librispeech(dataset, num_batches=2618)

6 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InternalError: libdevice not found at ./libdevice.10.bc [Op:__inference_tf_forward_55230]
```

Here's a screenshot:

<img width="1433" alt="Screen Shot 2022-01-09 at 2 18 26 PM" src="https://user-images.githubusercontent.com/362851/148699297-69bd41f1-20e2-4c11-9de7-7ffbf927084f.png">

**Comment by thevasudevgupta** [comment]
Hi,
it was happening because colab was unable to re-install tensorflow properly because of some reason. I have removed `tensorflow` from the `requirements.txt` as the fix. So, you should be able to run the notebooks now!!

Feel free to open the issue again if you encounter any other problem.
