### ISSUE TITLE
checkpoints LICENCE discussion

### ISSUE THREAD

**Issue by vasudevgupta7** [vasudevgupta7/gsoc-wav2vec2#4]
@sayakpaul @MorganR,

I converted checkpoint from [HuggingFace Transformers version](https://github.com/huggingface/transformers/blob/master/LICENSE) (they converted it from [fairseq](https://github.com/pytorch/fairseq/tree/master/examples/wav2vec)). `Huggingface Transformers` is `Apache` & `fairseq` is `MIT`.

So we are good to add ckpts to TF Hub right??

**Comment by sayakpaul** [comment]
Yup. Should be.
